//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.tradeblotterSampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class Data { }
#else

	public class Data : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public Data()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/SeattleSlewSketch_Ribbon.Screens;component/SampleData/tradeblotterSampleDataSource/tradeblotterSampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private rowCollection _rowCollection = new rowCollection();

		public rowCollection rowCollection
		{
			get
			{
				return this._rowCollection;
			}
		}
	}

	public class row : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _PortfolioBaseCode = string.Empty;

		public string PortfolioBaseCode
		{
			get
			{
				return this._PortfolioBaseCode;
			}

			set
			{
				if (this._PortfolioBaseCode != value)
				{
					this._PortfolioBaseCode = value;
					this.OnPropertyChanged("PortfolioBaseCode");
				}
			}
		}

		private double _TradeBlotterLineID = 0;

		public double TradeBlotterLineID
		{
			get
			{
				return this._TradeBlotterLineID;
			}

			set
			{
				if (this._TradeBlotterLineID != value)
				{
					this._TradeBlotterLineID = value;
					this.OnPropertyChanged("TradeBlotterLineID");
				}
			}
		}

		private double _SequenceNo = 0;

		public double SequenceNo
		{
			get
			{
				return this._SequenceNo;
			}

			set
			{
				if (this._SequenceNo != value)
				{
					this._SequenceNo = value;
					this.OnPropertyChanged("SequenceNo");
				}
			}
		}

		private double _RecID = 0;

		public double RecID
		{
			get
			{
				return this._RecID;
			}

			set
			{
				if (this._RecID != value)
				{
					this._RecID = value;
					this.OnPropertyChanged("RecID");
				}
			}
		}

		private double _PortfolioID = 0;

		public double PortfolioID
		{
			get
			{
				return this._PortfolioID;
			}

			set
			{
				if (this._PortfolioID != value)
				{
					this._PortfolioID = value;
					this.OnPropertyChanged("PortfolioID");
				}
			}
		}

		private string _TransactionCode = string.Empty;

		public string TransactionCode
		{
			get
			{
				return this._TransactionCode;
			}

			set
			{
				if (this._TransactionCode != value)
				{
					this._TransactionCode = value;
					this.OnPropertyChanged("TransactionCode");
				}
			}
		}

		private string _Comment = string.Empty;

		public string Comment
		{
			get
			{
				return this._Comment;
			}

			set
			{
				if (this._Comment != value)
				{
					this._Comment = value;
					this.OnPropertyChanged("Comment");
				}
			}
		}

		private string _Type1 = string.Empty;

		public string Type1
		{
			get
			{
				return this._Type1;
			}

			set
			{
				if (this._Type1 != value)
				{
					this._Type1 = value;
					this.OnPropertyChanged("Type1");
				}
			}
		}

		private string _Symbol1 = string.Empty;

		public string Symbol1
		{
			get
			{
				return this._Symbol1;
			}

			set
			{
				if (this._Symbol1 != value)
				{
					this._Symbol1 = value;
					this.OnPropertyChanged("Symbol1");
				}
			}
		}

		private double _SecurityID1 = 0;

		public double SecurityID1
		{
			get
			{
				return this._SecurityID1;
			}

			set
			{
				if (this._SecurityID1 != value)
				{
					this._SecurityID1 = value;
					this.OnPropertyChanged("SecurityID1");
				}
			}
		}

		private string _TradeDate = string.Empty;

		public string TradeDate
		{
			get
			{
				return this._TradeDate;
			}

			set
			{
				if (this._TradeDate != value)
				{
					this._TradeDate = value;
					this.OnPropertyChanged("TradeDate");
				}
			}
		}

		private string _SettleDate = string.Empty;

		public string SettleDate
		{
			get
			{
				return this._SettleDate;
			}

			set
			{
				if (this._SettleDate != value)
				{
					this._SettleDate = value;
					this.OnPropertyChanged("SettleDate");
				}
			}
		}

		private string _Quantity = string.Empty;

		public string Quantity
		{
			get
			{
				return this._Quantity;
			}

			set
			{
				if (this._Quantity != value)
				{
					this._Quantity = value;
					this.OnPropertyChanged("Quantity");
				}
			}
		}

		private string _ClosingMethodCode = string.Empty;

		public string ClosingMethodCode
		{
			get
			{
				return this._ClosingMethodCode;
			}

			set
			{
				if (this._ClosingMethodCode != value)
				{
					this._ClosingMethodCode = value;
					this.OnPropertyChanged("ClosingMethodCode");
				}
			}
		}

		private string _Type2 = string.Empty;

		public string Type2
		{
			get
			{
				return this._Type2;
			}

			set
			{
				if (this._Type2 != value)
				{
					this._Type2 = value;
					this.OnPropertyChanged("Type2");
				}
			}
		}

		private string _Symbol2 = string.Empty;

		public string Symbol2
		{
			get
			{
				return this._Symbol2;
			}

			set
			{
				if (this._Symbol2 != value)
				{
					this._Symbol2 = value;
					this.OnPropertyChanged("Symbol2");
				}
			}
		}

		private double _SecurityID2 = 0;

		public double SecurityID2
		{
			get
			{
				return this._SecurityID2;
			}

			set
			{
				if (this._SecurityID2 != value)
				{
					this._SecurityID2 = value;
					this.OnPropertyChanged("SecurityID2");
				}
			}
		}

		private string _TradeDateFX = string.Empty;

		public string TradeDateFX
		{
			get
			{
				return this._TradeDateFX;
			}

			set
			{
				if (this._TradeDateFX != value)
				{
					this._TradeDateFX = value;
					this.OnPropertyChanged("TradeDateFX");
				}
			}
		}

		private string _SettleDateFX = string.Empty;

		public string SettleDateFX
		{
			get
			{
				return this._SettleDateFX;
			}

			set
			{
				if (this._SettleDateFX != value)
				{
					this._SettleDateFX = value;
					this.OnPropertyChanged("SettleDateFX");
				}
			}
		}

		private string _OriginalFX = string.Empty;

		public string OriginalFX
		{
			get
			{
				return this._OriginalFX;
			}

			set
			{
				if (this._OriginalFX != value)
				{
					this._OriginalFX = value;
					this.OnPropertyChanged("OriginalFX");
				}
			}
		}

		private double _MarkToMarket = 0;

		public double MarkToMarket
		{
			get
			{
				return this._MarkToMarket;
			}

			set
			{
				if (this._MarkToMarket != value)
				{
					this._MarkToMarket = value;
					this.OnPropertyChanged("MarkToMarket");
				}
			}
		}

		private string _TradeAmount = string.Empty;

		public string TradeAmount
		{
			get
			{
				return this._TradeAmount;
			}

			set
			{
				if (this._TradeAmount != value)
				{
					this._TradeAmount = value;
					this.OnPropertyChanged("TradeAmount");
				}
			}
		}

		private string _OriginalCost = string.Empty;

		public string OriginalCost
		{
			get
			{
				return this._OriginalCost;
			}

			set
			{
				if (this._OriginalCost != value)
				{
					this._OriginalCost = value;
					this.OnPropertyChanged("OriginalCost");
				}
			}
		}

		private string _BuySellAI = string.Empty;

		public string BuySellAI
		{
			get
			{
				return this._BuySellAI;
			}

			set
			{
				if (this._BuySellAI != value)
				{
					this._BuySellAI = value;
					this.OnPropertyChanged("BuySellAI");
				}
			}
		}

		private string _WithholdingTax = string.Empty;

		public string WithholdingTax
		{
			get
			{
				return this._WithholdingTax;
			}

			set
			{
				if (this._WithholdingTax != value)
				{
					this._WithholdingTax = value;
					this.OnPropertyChanged("WithholdingTax");
				}
			}
		}

		private double _ExchangeID = 0;

		public double ExchangeID
		{
			get
			{
				return this._ExchangeID;
			}

			set
			{
				if (this._ExchangeID != value)
				{
					this._ExchangeID = value;
					this.OnPropertyChanged("ExchangeID");
				}
			}
		}

		private string _ExchangeFee = string.Empty;

		public string ExchangeFee
		{
			get
			{
				return this._ExchangeFee;
			}

			set
			{
				if (this._ExchangeFee != value)
				{
					this._ExchangeFee = value;
					this.OnPropertyChanged("ExchangeFee");
				}
			}
		}

		private string _Commission = string.Empty;

		public string Commission
		{
			get
			{
				return this._Commission;
			}

			set
			{
				if (this._Commission != value)
				{
					this._Commission = value;
					this.OnPropertyChanged("Commission");
				}
			}
		}

		private string _OtherFees = string.Empty;

		public string OtherFees
		{
			get
			{
				return this._OtherFees;
			}

			set
			{
				if (this._OtherFees != value)
				{
					this._OtherFees = value;
					this.OnPropertyChanged("OtherFees");
				}
			}
		}

		private double _CommissionPurposeID = 0;

		public double CommissionPurposeID
		{
			get
			{
				return this._CommissionPurposeID;
			}

			set
			{
				if (this._CommissionPurposeID != value)
				{
					this._CommissionPurposeID = value;
					this.OnPropertyChanged("CommissionPurposeID");
				}
			}
		}

		private double _CustodianID = 0;

		public double CustodianID
		{
			get
			{
				return this._CustodianID;
			}

			set
			{
				if (this._CustodianID != value)
				{
					this._CustodianID = value;
					this.OnPropertyChanged("CustodianID");
				}
			}
		}

		private double _DestCustodianID = 0;

		public double DestCustodianID
		{
			get
			{
				return this._DestCustodianID;
			}

			set
			{
				if (this._DestCustodianID != value)
				{
					this._DestCustodianID = value;
					this.OnPropertyChanged("DestCustodianID");
				}
			}
		}

		private string _OriginalFace = string.Empty;

		public string OriginalFace
		{
			get
			{
				return this._OriginalFace;
			}

			set
			{
				if (this._OriginalFace != value)
				{
					this._OriginalFace = value;
					this.OnPropertyChanged("OriginalFace");
				}
			}
		}

		private string _YieldOnCost = string.Empty;

		public string YieldOnCost
		{
			get
			{
				return this._YieldOnCost;
			}

			set
			{
				if (this._YieldOnCost != value)
				{
					this._YieldOnCost = value;
					this.OnPropertyChanged("YieldOnCost");
				}
			}
		}

		private string _DurationOnCost = string.Empty;

		public string DurationOnCost
		{
			get
			{
				return this._DurationOnCost;
			}

			set
			{
				if (this._DurationOnCost != value)
				{
					this._DurationOnCost = value;
					this.OnPropertyChanged("DurationOnCost");
				}
			}
		}

		private double _UserDefinedID1 = 0;

		public double UserDefinedID1
		{
			get
			{
				return this._UserDefinedID1;
			}

			set
			{
				if (this._UserDefinedID1 != value)
				{
					this._UserDefinedID1 = value;
					this.OnPropertyChanged("UserDefinedID1");
				}
			}
		}

		private double _UserDefinedID2 = 0;

		public double UserDefinedID2
		{
			get
			{
				return this._UserDefinedID2;
			}

			set
			{
				if (this._UserDefinedID2 != value)
				{
					this._UserDefinedID2 = value;
					this.OnPropertyChanged("UserDefinedID2");
				}
			}
		}

		private double _UserDefinedID3 = 0;

		public double UserDefinedID3
		{
			get
			{
				return this._UserDefinedID3;
			}

			set
			{
				if (this._UserDefinedID3 != value)
				{
					this._UserDefinedID3 = value;
					this.OnPropertyChanged("UserDefinedID3");
				}
			}
		}

		private double _TranID = 0;

		public double TranID
		{
			get
			{
				return this._TranID;
			}

			set
			{
				if (this._TranID != value)
				{
					this._TranID = value;
					this.OnPropertyChanged("TranID");
				}
			}
		}

		private double _IPCounter = 0;

		public double IPCounter
		{
			get
			{
				return this._IPCounter;
			}

			set
			{
				if (this._IPCounter != value)
				{
					this._IPCounter = value;
					this.OnPropertyChanged("IPCounter");
				}
			}
		}

		private string _Replace = string.Empty;

		public string Replace
		{
			get
			{
				return this._Replace;
			}

			set
			{
				if (this._Replace != value)
				{
					this._Replace = value;
					this.OnPropertyChanged("Replace");
				}
			}
		}

		private double _SourceID = 0;

		public double SourceID
		{
			get
			{
				return this._SourceID;
			}

			set
			{
				if (this._SourceID != value)
				{
					this._SourceID = value;
					this.OnPropertyChanged("SourceID");
				}
			}
		}

		private double _OmnibusID = 0;

		public double OmnibusID
		{
			get
			{
				return this._OmnibusID;
			}

			set
			{
				if (this._OmnibusID != value)
				{
					this._OmnibusID = value;
					this.OnPropertyChanged("OmnibusID");
				}
			}
		}

		private string _Recon = string.Empty;

		public string Recon
		{
			get
			{
				return this._Recon;
			}

			set
			{
				if (this._Recon != value)
				{
					this._Recon = value;
					this.OnPropertyChanged("Recon");
				}
			}
		}

		private string _Hold = string.Empty;

		public string Hold
		{
			get
			{
				return this._Hold;
			}

			set
			{
				if (this._Hold != value)
				{
					this._Hold = value;
					this.OnPropertyChanged("Hold");
				}
			}
		}

		private string _ReclaimAmount = string.Empty;

		public string ReclaimAmount
		{
			get
			{
				return this._ReclaimAmount;
			}

			set
			{
				if (this._ReclaimAmount != value)
				{
					this._ReclaimAmount = value;
					this.OnPropertyChanged("ReclaimAmount");
				}
			}
		}

		private double _StrategyID = 0;

		public double StrategyID
		{
			get
			{
				return this._StrategyID;
			}

			set
			{
				if (this._StrategyID != value)
				{
					this._StrategyID = value;
					this.OnPropertyChanged("StrategyID");
				}
			}
		}

		private string _RecordDate = string.Empty;

		public string RecordDate
		{
			get
			{
				return this._RecordDate;
			}

			set
			{
				if (this._RecordDate != value)
				{
					this._RecordDate = value;
					this.OnPropertyChanged("RecordDate");
				}
			}
		}

		private string _DivIncomeSymbol = string.Empty;

		public string DivIncomeSymbol
		{
			get
			{
				return this._DivIncomeSymbol;
			}

			set
			{
				if (this._DivIncomeSymbol != value)
				{
					this._DivIncomeSymbol = value;
					this.OnPropertyChanged("DivIncomeSymbol");
				}
			}
		}

		private string _DivAccrualSymbol = string.Empty;

		public string DivAccrualSymbol
		{
			get
			{
				return this._DivAccrualSymbol;
			}

			set
			{
				if (this._DivAccrualSymbol != value)
				{
					this._DivAccrualSymbol = value;
					this.OnPropertyChanged("DivAccrualSymbol");
				}
			}
		}

		private string _DivAccrualMethodCode = string.Empty;

		public string DivAccrualMethodCode
		{
			get
			{
				return this._DivAccrualMethodCode;
			}

			set
			{
				if (this._DivAccrualMethodCode != value)
				{
					this._DivAccrualMethodCode = value;
					this.OnPropertyChanged("DivAccrualMethodCode");
				}
			}
		}

		private double _BrokerFirmID = 0;

		public double BrokerFirmID
		{
			get
			{
				return this._BrokerFirmID;
			}

			set
			{
				if (this._BrokerFirmID != value)
				{
					this._BrokerFirmID = value;
					this.OnPropertyChanged("BrokerFirmID");
				}
			}
		}

		private double _MatchID = 0;

		public double MatchID
		{
			get
			{
				return this._MatchID;
			}

			set
			{
				if (this._MatchID != value)
				{
					this._MatchID = value;
					this.OnPropertyChanged("MatchID");
				}
			}
		}

		private string _SRRecon = string.Empty;

		public string SRRecon
		{
			get
			{
				return this._SRRecon;
			}

			set
			{
				if (this._SRRecon != value)
				{
					this._SRRecon = value;
					this.OnPropertyChanged("SRRecon");
				}
			}
		}

		private string _LabelName = string.Empty;

		public string LabelName
		{
			get
			{
				return this._LabelName;
			}

			set
			{
				if (this._LabelName != value)
				{
					this._LabelName = value;
					this.OnPropertyChanged("LabelName");
				}
			}
		}

		private double _NLabelValuePrec = 0;

		public double NLabelValuePrec
		{
			get
			{
				return this._NLabelValuePrec;
			}

			set
			{
				if (this._NLabelValuePrec != value)
				{
					this._NLabelValuePrec = value;
					this.OnPropertyChanged("NLabelValuePrec");
				}
			}
		}

		private string _SLabelValue = string.Empty;

		public string SLabelValue
		{
			get
			{
				return this._SLabelValue;
			}

			set
			{
				if (this._SLabelValue != value)
				{
					this._SLabelValue = value;
					this.OnPropertyChanged("SLabelValue");
				}
			}
		}

		private double _BlotterID = 0;

		public double BlotterID
		{
			get
			{
				return this._BlotterID;
			}

			set
			{
				if (this._BlotterID != value)
				{
					this._BlotterID = value;
					this.OnPropertyChanged("BlotterID");
				}
			}
		}

		private double _AuditEventID = 0;

		public double AuditEventID
		{
			get
			{
				return this._AuditEventID;
			}

			set
			{
				if (this._AuditEventID != value)
				{
					this._AuditEventID = value;
					this.OnPropertyChanged("AuditEventID");
				}
			}
		}

		private string _AuditTypeCode = string.Empty;

		public string AuditTypeCode
		{
			get
			{
				return this._AuditTypeCode;
			}

			set
			{
				if (this._AuditTypeCode != value)
				{
					this._AuditTypeCode = value;
					this.OnPropertyChanged("AuditTypeCode");
				}
			}
		}

		private string _AuditTimestamp = string.Empty;

		public string AuditTimestamp
		{
			get
			{
				return this._AuditTimestamp;
			}

			set
			{
				if (this._AuditTimestamp != value)
				{
					this._AuditTimestamp = value;
					this.OnPropertyChanged("AuditTimestamp");
				}
			}
		}

		private double _SRReconTranID = 0;

		public double SRReconTranID
		{
			get
			{
				return this._SRReconTranID;
			}

			set
			{
				if (this._SRReconTranID != value)
				{
					this._SRReconTranID = value;
					this.OnPropertyChanged("SRReconTranID");
				}
			}
		}

		private double _ApplyToShortPosition = 0;

		public double ApplyToShortPosition
		{
			get
			{
				return this._ApplyToShortPosition;
			}

			set
			{
				if (this._ApplyToShortPosition != value)
				{
					this._ApplyToShortPosition = value;
					this.OnPropertyChanged("ApplyToShortPosition");
				}
			}
		}

		private double _EstDividendState = 0;

		public double EstDividendState
		{
			get
			{
				return this._EstDividendState;
			}

			set
			{
				if (this._EstDividendState != value)
				{
					this._EstDividendState = value;
					this.OnPropertyChanged("EstDividendState");
				}
			}
		}
	}

	public class rowCollection : System.Collections.ObjectModel.ObservableCollection<row>
	{ 
	}
#endif
}
